version: '3'
services:
  mysql:
    image: mysql:8-oracle
    container_name: marketplace-database
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace